// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6jxXVizHyHEH6pYnWCE0b1w4bqAUg_5E',
    appId: '1:507276548746:web:a336c576297a5335d56b73',
    messagingSenderId: '507276548746',
    projectId: 'bill-track-b5a22',
    authDomain: 'bill-track-b5a22.firebaseapp.com',
    storageBucket: 'bill-track-b5a22.firebasestorage.app',
    measurementId: 'G-JW86KJZ17T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZa4aAu1oOStzIRMb241PT_NQlpagfP74',
    appId: '1:507276548746:android:c6ee08a7d73aad6cd56b73',
    messagingSenderId: '507276548746',
    projectId: 'bill-track-b5a22',
    storageBucket: 'bill-track-b5a22.firebasestorage.app',
    iosClientId: '507276548746-958lbq5qq0k787go58nq24t8dh2pdq7c.apps.googleusercontent.com', 
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTrPtPFAXHXODBiwTQtyMivXs25M6P8mc',
    appId: '1:507276548746:ios:18b6ccab748b725ad56b73',
    messagingSenderId: '507276548746',
    projectId: 'bill-track-b5a22',
    storageBucket: 'bill-track-b5a22.firebasestorage.app',
    iosClientId: '507276548746-k7v807apmi3lnsa3mdkavsh522v4srm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.billtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTrPtPFAXHXODBiwTQtyMivXs25M6P8mc',
    appId: '1:507276548746:ios:18b6ccab748b725ad56b73',
    messagingSenderId: '507276548746',
    projectId: 'bill-track-b5a22',
    storageBucket: 'bill-track-b5a22.firebasestorage.app',
    iosClientId: '507276548746-k7v807apmi3lnsa3mdkavsh522v4srm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.billtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6jxXVizHyHEH6pYnWCE0b1w4bqAUg_5E',
    appId: '1:507276548746:web:0ec7015ba2a37d4fd56b73',
    messagingSenderId: '507276548746',
    projectId: 'bill-track-b5a22',
    authDomain: 'bill-track-b5a22.firebaseapp.com',
    storageBucket: 'bill-track-b5a22.firebasestorage.app',
    measurementId: 'G-B2KBXECRYY',
  );
}
